### ISSUE TITLE
bold text

### ISSUE THREAD

**Issue by rmad17** [dannynimmo/punctual-zsh-theme#1]
Is there anyway to make some text bold like username?

**Comment by dannynimmo** [comment]
I should be able to sort something out. I'll take a look when I next get a chance.

**Comment by rmad17** [comment]
Also could you check if virtualenv could be integrated a little more nicely? Really nice theme btw.

**Comment by dannynimmo** [comment]
@rmad17 I've added support for configuring bold fonts in [v0.2.0](https://github.com/dannynimmo/punctual-zsh-theme/releases/tag/v0.2.0).

As for your second request, I personally don't use Python so I won't be adding this myself. I've set up issue #2 if you want to send a pull request, or for anyone else who wants to contribute.
