### ISSUE TITLE
Idea: Removing initial blank line; it is possible?

### ISSUE THREAD

**Issue by VetAran** [dannynimmo/punctual-zsh-theme#3]
When you start the terminal there is a space between the top and the initial text output. Can this space be removed to better identify the starting point?

I love your theme. Excellent job!

_diortem

**Comment by dannynimmo** [comment]
Hey @diortem, thanks for your feedback. I've added an option for you to disable the initial new line. Just add the below configuration variable before you load the theme, and make sure you update to the latest version.

```sh
PUNCTUAL_SHOW_BLANK_LINE='false';
```
