### ISSUE TITLE
Align conda env name

### ISSUE THREAD

**Issue by shelfofclub** [dannynimmo/punctual-zsh-theme#5]
Could you align conda env name with the second line prompt?
![image](https://user-images.githubusercontent.com/32047804/143767947-b7357a53-ee43-4254-aa7a-f7657baec3cf.png)
I think this may be like "virtualenv could be integrated a little more nicely“ in #1.

The environment name seems to be added by conda. There are two environment variables set by conda. When a conda env is activated, `CONDA_DEFAULT_ENV` and `CONDA_PROMPT_MODIFIER` are set. For examples,
>CONDA_DEFAULT_ENV=base
CONDA_PROMPT_MODIFIER=(base)

When conda env not activated, these env variables don't exit.
However, as for #2 , virtualenv may use different enc variables.

And `changeps1: False` in conda config file can prevent conda change prompt.

Thank you!

**Comment by dannynimmo** [comment]
Fixed in #6
