### ISSUE TITLE
Git symbols don't show up any more

### ISSUE THREAD

**Issue by sparusaurata** [dannynimmo/punctual-zsh-theme#7]
Since a couple of months, the symbols indicating the status of a git repo don't appear any more. The name of the branch is still there. I wonder where the problem is, I haven't been able to understand it.

(I'm using Linux Mint 21.2 with zsh 5.8.1, and an updated oh-my-zsh.)

**Comment by dannynimmo** [comment]
@sparusaurata try adding the below to your `.zshrc` before omz:
```sh
zstyle ':omz:alpha:lib:git' async-prompt false;
```

**Comment by sparusaurata** [comment]
It works, thanks!
